### ISSUE TITLE
separate core/data input pipeline ?

### ISSUE THREAD

**Issue by MKorablyov** [mitaffinity/core#1]
I am thinking that it's a good idea if we:

1) Create a separate project and 
alternative is to leave it as a folder called input preprocessing
2) Merge everything with Yi's code
3) Add proper annotations to the top of every script
4) remove Orchestra specific scripts that were used to submit the jobs (or at least save them separately)

**Comment by Reimilia** [comment]
I suggest a new repository , say data_preprocessing, to merge all the codes related on how to get our raw input in the network

**Comment by MKorablyov** [comment]
Yi, was a good solution. I saw your new code arrived in the last couple of nights. So far so good.
