### ISSUE TITLE
would sparse_to_dense work right when the indexes are not validated

### ISSUE THREAD

**Issue by MKorablyov** [mitaffinity/core#16]
this relates to #14 

Nilai, can we be sure that sparse_to_dense works right when indexes are not validated ?
Mina is using it now. If yes. you can close this issue

**Comment by meng-sun** [comment]
Confirmed. Validate=False does print the same dense tensor as a sorted version of sparse tensor.

**Comment by meng-sun** [comment]
Confirmed. Validate=False does print the same dense tensor as a sorted version of sparse tensor.
