### ISSUE TITLE
new submission format

### ISSUE THREAD

**Issue by MKorablyov** [mitaffinity/core#5]
We have changed Kaggle competition to DUD-E, and now need a default script to write a new submission format for Kaggle's AUC calculations.

**Comment by LXander** [comment]
Currently, the output file contains multiple predictions for multiple frames, I can add another output file takes average of multiple predictions so people can submit it on kaggle after evaluation is done.

**Comment by MKorablyov** [comment]
Yes. That's a good idea. I would be up for writing a single file with predictions, IE: the one we have now.
And we can write many different functions that can analyze it, maybe, in the same script

**Comment by MKorablyov** [comment]
Xiao, many thanks for the single file - in the future we can train simple models on it.
